version: '3.7'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.4
    ports:
      - 5433:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /PATH/TO/DATA/DIRECTORY:/projects/pfas/data
    env_file:
      - ./.env.dev.db
volumes:
  postgres_data:
