version: '3.7'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn pfasdata.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mdillon/postgis:11
    ports:
      - 5432:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /projects/pfas/data:/projects/pfas/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
