version: '3.7'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn pfasdata.wsgi:application --certfile=/etc/ssl/SSL.crt --keyfile=/etc/ssl/SSL.key --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
      - /data/certs/pfas-db-dev_mdc_renci_unc_edu_public.cer:/etc/ssl/SSL.crt
      - /data/certs/pfas-db-dev_mdc_renci_unc_edu_private.key:/etc/ssl/SSL.key
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.4
    ports:
      - 5433:${SQL_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /projects/pfas/data:/projects/pfas/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/home/django/web/staticfiles
      - media_volume:/home/django/web/mediafiles
      - /data/certs/pfas-db-dev_mdc_renci_unc_edu_public.cer:/etc/ssl/SSL.crt
      - /data/certs/pfas-db-dev_mdc_renci_unc_edu_private.key:/etc/ssl/SSL.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
